name: by_interview
channels:
        - defaults
dependencies:
        # data
        - pandas
        - numpy

        # ml
        - scikit-learn

        # jupyter
        - jupyter
        - jupyterlab

        # plotting
        - matplotlib
        - seaborn
